name: Adicionar evento (Agenda Tech Brasil)

          git push
  issues:
    types: [opened]


  adicionar_evento:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Extrair dados da issue
        id: extract
        run: |
          echo "EVENT_NAME=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Nome do Evento' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "EVENT_YEAR=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Ano do Evento' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "EVENT_MONTH=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Mês do Evento' | tail -n1 | xargs | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "EVENT_DAY=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Dia do Evento' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "EVENT_URL=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'URL do Evento' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "EVENT_CITY=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Cidade' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "EVENT_STATE=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'UF' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "EVENT_TYPE=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Tipo' | tail -n1 | xargs)" >> $GITHUB_ENV

      - name: Adicionar evento ao banco de dados
        run: |
          python .github/workflows/Add_evet.py
        env:
          event_name: ${{ env.EVENT_NAME }}
          event_year: ${{ env.EVENT_YEAR }}
          event_month: ${{ env.EVENT_MONTH }}
          event_day: ${{ env.EVENT_DAY }}
          event_url: ${{ env.EVENT_URL }}
          event_city: ${{ env.EVENT_CITY }}
          event_state: ${{ env.EVENT_STATE }}
          event_type: ${{ env.EVENT_TYPE }}

      - name: Commit e push se houver mudanças
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add db/database.json || true
          git commit -m "Adiciona evento automaticamente via issue" || exit 0
          git push
          git config --global user.name "github-actions[bot]"
