name: Update event

on:
  issues:
    types: [opened]

jobs:
  update_event:
    if: |
      github.event.issue.title == null || startsWith(github.event.issue.title, '(Atenção:')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Extract issue data
        id: extract
        run: |
          echo "EVENT_NAME=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Nome do Evento' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "EVENT_YEAR=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Ano do Evento' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "EVENT_MONTH=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Mês do Evento' | tail -n1 | xargs | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "EVENT_DAY=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Dia do Evento' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "EVENT_URL=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'URL do Evento' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "EVENT_CITY=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Cidade' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "EVENT_STATE=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'UF' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "EVENT_TYPE=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Tipo' | tail -n1 | xargs)" >> $GITHUB_ENV

      - name: Update event in database
        run: |
          python .github/workflows/Update_event.py
        env:
          event_name: ${{ env.EVENT_NAME }}
          event_year: ${{ env.EVENT_YEAR }}
          event_month: ${{ env.EVENT_MONTH }}
          event_day: ${{ env.EVENT_DAY }}
          event_url: ${{ env.EVENT_URL }}
          event_city: ${{ env.EVENT_CITY }}
          event_state: ${{ env.EVENT_STATE }}
          event_type: ${{ env.EVENT_TYPE }}

      - name: Commit and push if changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add db/database.json || true
          git commit -m "Automatically update event via issue" || exit 0
          git push
