name: Update event

on:
  issues:
    types: [opened]

jobs:
  update_event:
    if: |
      github.event.issue.title == null || startsWith(github.event.issue.title, '(Atenção:')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Extract issue data
        id: extract
        run: |
          echo "NOME_EVENTO=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Nome do Evento' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "ANO_EVENTO=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Ano do Evento' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "MES_EVENTO=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Mês do Evento' | tail -n1 | xargs | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "DIAS_EVENTO=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Dias do Evento' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "URL_EVENTO=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Site do Evento' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "CIDADE_EVENTO=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Cidade do Evento' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "ESTADO_EVENTO=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Estado do Evento' | tail -n1 | xargs)" >> $GITHUB_ENV
          echo "TIPO_EVENTO=$(jq -r '.issue.body' \"$GITHUB_EVENT_PATH\" | grep -A1 'Tipo do Evento' | tail -n1 | xargs)" >> $GITHUB_ENV

      - name: Update event in database
        run: |
          python .github/workflows/Update_event.py
        env:
          nome_evento: ${{ env.NOME_EVENTO }}
          ano_evento: ${{ env.ANO_EVENTO }}
          mes_evento: ${{ env.MES_EVENTO }}
          dias_evento: ${{ env.DIAS_EVENTO }}
          url_evento: ${{ env.URL_EVENTO }}
          cidade_evento: ${{ env.CIDADE_EVENTO }}
          estado_evento: ${{ env.ESTADO_EVENTO }}
          tipo_evento: ${{ env.TIPO_EVENTO }}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add db/database.json || true
          git commit -m "Atualização automática de evento via issue" || exit 0
          git push